loading final test folder from git

diff --git a/test/integration b/test/integration
--- a/test/integration
+++ b/test/integration
@@ -14,11 +14,14 @@ set -eu
 
 readonly DIR=$(dirname "$(readlink -f "$0")")
 
+# Location to builddir.
+readonly BUILD_DIR="${BUILD_DIR:-$DIR/../build}"
+
 # Location containing examples.
 readonly EXAMPLES_DIR="${EXAMPLES_DIR:-$DIR/../doc/examples}"
 
 # mC compiler binary.
-readonly MCC="${MCC:-./mCc}"
+readonly MCC="${MCC:-../build/mCc}"
 
 # colour support
 if [[ -t 1 ]]; then
@@ -39,13 +42,6 @@ option_csv=false
 
 # ------------------------------------------------------------------- FUNCTIONS
 
-run_compiler()
-{
-	local input=$1
-	\time -f "%e %M %x" "$MCC" "$input" 2>&1 | tail -n1
-	return ${PIPESTATUS[0]}
-}
-
 print_header_md()
 {
 	echo "Input                                             Time        Memory  Status"
@@ -55,6 +51,13 @@ print_header_md()
 print_header_csv()
 {
 	echo "Input,Time [s],Memory [kB],Status"
+}
+
+run_compiler()
+{
+	local input=$1
+	\time -f "%e %M %x" "$MCC" "$input" -o ../build/integration.out 2>&1 | tail -n1
+	return ${PIPESTATUS[0]}
 }
 
 print_run_md()
@@ -177,6 +180,21 @@ print_header
 
 		if [[ $(echo $stats | cut -d ' ' -f3) -ne 0 ]]; then
 			flawless=false
+		fi
+
+        # Execute the generated binary with the corresponding input and compare outputs
+		if [[ -e "$BUILD_DIR/./integration.out" ]]; then
+            if [ "$("$BUILD_DIR/./integration.out" < "$EXAMPLES_DIR/$example.stdin")" != "$(cat $EXAMPLES_DIR/$example.stdout)" ]; then
+                flawless=false
+                stats="- - 1"
+                echo "no match output"
+  #              echo "$("$BUILD_DIR/./integration.out" < "$EXAMPLES_DIR/$example.stdin")"
+ #               echo "$(cat $EXAMPLES_DIR/$example.stdout)"
+            fi
+        else
+            flawless=false
+            stats="- - 1"
+            #echo "BINARY NOT FOUND"
 		fi
 
 		print_run "$example" $stats
